export type ModuleDefinition = {
  id: string;
  label: string;
  description: string;
  icon: string;
  category: 'core' | 'sales' | 'procurement' | 'inventory' | 'projects' | 'hr' | 'reports';
  route?: string;
};

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    description: 'Central hub with KPIs, widgets, and quick actions.',
    icon: 'LayoutDashboard',
    category: 'core',
    route: '/',
  },
  {
    id: 'projects',
    label: 'Projects',
    description: 'End-to-end project tracking, milestones, and site materials.',
    icon: 'FolderKanban',
    category: 'projects',
    route: '/projects',
  },
  {
    id: 'clients',
    label: 'Clients',
    description: 'Client directory, profiles, and relationship management.',
    icon: 'Users',
    category: 'sales',
    route: '/clients',
  },
  {
    id: 'quotations',
    label: 'Quotations',
    description: 'Create, track, and manage sales quotations.',
    icon: 'FileText',
    category: 'sales',
    route: '/quotation',
  },
  {
    id: 'invoices',
    label: 'Invoices',
    description: 'Billing, invoicing, and payment tracking.',
    icon: 'Receipt',
    category: 'sales',
    route: '/invoices',
  },
  {
    id: 'proforma_invoices',
    label: 'Proforma Invoices',
    description: 'Pre-billing documents for advance payment or estimation.',
    icon: 'FileCheck',
    category: 'sales',
    route: '/proforma-invoices',
  },
  {
    id: 'credit_notes',
    label: 'Credit Notes',
    description: 'Issue credit notes and manage adjustments.',
    icon: 'FileMinus',
    category: 'sales',
    route: '/credit-notes',
  },
  {
    id: 'delivery_challans',
    label: 'Delivery Challans',
    description: 'Material delivery tracking and DC management.',
    icon: 'Truck',
    category: 'inventory',
    route: '/dc/list',
  },
  {
    id: 'client_purchase_orders',
    label: 'Client Purchase Orders',
    description: 'Receive and manage client POs.',
    icon: 'ShoppingCart',
    category: 'sales',
    route: '/client-po',
  },
  {
    id: 'materials',
    label: 'Materials & Inventory',
    description: 'Material master, stock levels, and inventory operations.',
    icon: 'Package',
    category: 'inventory',
    route: '/store/materials',
  },
  {
    id: 'material_intents',
    label: 'Material Intents',
    description: 'Material requisitions, intent tracking, and stock allocation.',
    icon: 'ClipboardList',
    category: 'inventory',
    route: '/store/inward',
  },
  {
    id: 'stock_transfer',
    label: 'Stock Transfer',
    description: 'Inter-site and inter-warehouse stock movement.',
    icon: 'ArrowLeftRight',
    category: 'inventory',
    route: '/store/transfer',
  },
  {
    id: 'purchase',
    label: 'Purchase Module',
    description: 'Procurement lifecycle: requisitions, inquiries, POs, and vendor management.',
    icon: 'ShoppingBag',
    category: 'procurement',
    route: '/purchase',
  },
  {
    id: 'subcontractors',
    label: 'Sub-Contractors',
    description: 'Sub-contractor management, work orders, and payments.',
    icon: 'HardHat',
    category: 'projects',
    route: '/subcontractors',
  },
  {
    id: 'meetings',
    label: 'Meetings',
    description: 'Schedule, record, and track meeting minutes.',
    icon: 'Calendar',
    category: 'core',
    route: '/meetings',
  },
  {
    id: 'site_visits',
    label: 'Site Visits',
    description: 'Plan and log site visits with check-in/out.',
    icon: 'MapPin',
    category: 'projects',
    route: '/site-visits',
  },
  {
    id: 'site_reports',
    label: 'Site Reports',
    description: 'Daily progress, stoppages, and photo documentation.',
    icon: 'Clipboard',
    category: 'projects',
    route: '/site-reports',
  },
  {
    id: 'approvals',
    label: 'Approvals',
    description: 'Approval workflows and request management.',
    icon: 'CheckCircle',
    category: 'core',
    route: '/approvals',
  },
  {
    id: 'follow_up',
    label: 'Follow-Up Centre',
    description: 'Client follow-up tracking and reminders.',
    icon: 'Bell',
    category: 'sales',
    route: '/follow-up',
  },
  {
    id: 'tools_management',
    label: 'Tools Management',
    description: 'Track, assign, and manage project tools and equipment.',
    icon: 'Wrench',
    category: 'projects',
    route: '/tools',
  },
  {
    id: 'boq',
    label: 'Bill of Quantities',
    description: 'BOQ creation, line-item management, and cost tracking.',
    icon: 'TableProperties',
    category: 'projects',
    route: '/boq',
  },
  {
    id: 'manufacturing',
    label: 'Manufacturing',
    description: 'BOMs, production schedules, job cards, and activity logs.',
    icon: 'Factory',
    category: 'core',
    route: '/manufacturing',
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    description: 'Financial, project, inventory, and compliance reports.',
    icon: 'BarChart3',
    category: 'reports',
    route: '/reports',
  },
  {
    id: 'ledger',
    label: 'Ledger',
    description: 'Account ledger and financial transaction history.',
    icon: 'BookOpen',
    category: 'sales',
    route: '/ledger',
  },
  {
    id: 'daily_updates',
    label: 'Daily Updates',
    description: 'Daily work logs and team status updates.',
    icon: 'Clock',
    category: 'core',
    route: '/todo',
  },
];

export const MODULE_CATEGORIES: Record<string, { label: string; color: string }> = {
  core: { label: 'Core', color: '#171717' },
  sales: { label: 'Sales & Finance', color: '#2563eb' },
  procurement: { label: 'Procurement', color: '#7c3aed' },
  inventory: { label: 'Inventory', color: '#059669' },
  projects: { label: 'Projects & Sites', color: '#d97706' },
  hr: { label: 'HR & Attendance', color: '#dc2626' },
  reports: { label: 'Reports & Analytics', color: '#0891b2' },
};
