import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { GeneratedReport } from '../reports/api';

// Extend jsPDF with autoTable plugin
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface PDFTemplate {
  title: string;
  subtitle?: string;
  logo?: string;
  organization: string;
  generatedBy: string;
  generatedAt: string;
  filters?: Record<string, any>;
}

interface TableData {
  headers: string[];
  data: any[][];
  title?: string;
  footers?: string[][];
}

interface ChartData {
  type: 'bar' | 'line' | 'pie';
  title: string;
  data: any;
  width?: number;
  height?: number;
}

export interface PDFOptions {
  template: PDFTemplate;
  tables: TableData[];
  charts?: ChartData[];
  summary?: Array<{ label: string; value: string; trend?: string }>;
  pageSize?: 'a4' | 'a3' | 'letter';
  orientation?: 'portrait' | 'landscape';
  margins?: { top: number; right: number; bottom: number; left: number };
}

class PDFGenerator {
  private doc: jsPDF;
  private options: PDFOptions;
  private currentY: number;
  private pageHeight: number;
  private pageWidth: number;
  private margins: { top: number; right: number; bottom: number; left: number };

  constructor(options: PDFOptions) {
    this.options = options;
    this.margins = options.margins || { top: 20, right: 20, bottom: 20, left: 20 };
    
    this.doc = new jsPDF({
      orientation: options.orientation || 'portrait',
      unit: 'mm',
      format: options.pageSize || 'a4'
    });

    const pageSize = this.doc.internal.pageSize;
    this.pageWidth = pageSize.getWidth();
    this.pageHeight = pageSize.getHeight();
    this.currentY = this.margins.top;
  }

  generate(): Blob {
    this.addHeader();
    this.addSummary();
    this.addTables();
    this.addCharts();
    this.addFooter();
    
    return new Blob([this.doc.output('blob')], { type: 'application/pdf' });
  }

  private addHeader(): void {
    const { template } = this.options;
    
    // Company Logo (if provided)
    if (template.logo) {
      try {
        this.doc.addImage(template.logo, 'PNG', this.margins.left, this.currentY, 30, 20);
        this.currentY += 25;
      } catch (error) {
        console.warn('Failed to add logo to PDF:', error);
      }
    }

    // Report Title
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(33, 37, 41);
    this.doc.text(template.title, this.pageWidth / 2, this.currentY, { align: 'center' });
    this.currentY += 10;

    // Subtitle
    if (template.subtitle) {
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(107, 114, 128);
      this.doc.text(template.subtitle, this.pageWidth / 2, this.currentY, { align: 'center' });
      this.currentY += 8;
    }

    // Organization and Generation Info
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(107, 114, 128);
    
    const infoText = [
      `Organization: ${template.organization}`,
      `Generated by: ${template.generatedBy}`,
      `Generated at: ${template.generatedAt}`
    ];

    infoText.forEach(text => {
      this.doc.text(text, this.margins.left, this.currentY);
      this.currentY += 5;
    });

    // Add line separator
    this.currentY += 5;
    this.doc.setDrawColor(229, 231, 235);
    this.doc.setLineWidth(0.5);
    this.doc.line(this.margins.left, this.currentY, this.pageWidth - this.margins.right, this.currentY);
    this.currentY += 10;

    // Filters section
    if (template.filters && Object.keys(template.filters).length > 0) {
      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(33, 37, 41);
      this.doc.text('Applied Filters:', this.margins.left, this.currentY);
      this.currentY += 6;

      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(107, 114, 128);

      Object.entries(template.filters).forEach(([key, value]) => {
        const filterText = this.formatFilterValue(key, value);
        this.doc.text(filterText, this.margins.left + 5, this.currentY);
        this.currentY += 5;
      });

      this.currentY += 5;
    }
  }

  private addSummary(): void {
    if (!this.options.summary || this.options.summary.length === 0) return;

    this.checkPageBreak(40);

    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(33, 37, 41);
    this.doc.text('Executive Summary', this.margins.left, this.currentY);
    this.currentY += 10;

    // Summary boxes
    const boxWidth = (this.pageWidth - this.margins.left - this.margins.right - 15) / 2;
    const boxHeight = 25;

    this.options.summary.forEach((item, index) => {
      const x = index % 2 === 0 ? this.margins.left : this.margins.left + boxWidth + 15;
      const y = this.currentY + Math.floor(index / 2) * (boxHeight + 10);

      // Draw box
      this.doc.setDrawColor(229, 231, 235);
      this.doc.setFillColor(249, 250, 251);
      this.doc.roundedRect(x, y, boxWidth, boxHeight, 3, 3, 'FD');

      // Add content
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(107, 114, 128);
      this.doc.text(item.label, x + 8, y + 10);

      this.doc.setFontSize(16);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(33, 37, 41);
      this.doc.text(item.value, x + 8, y + 18);

      if (item.trend) {
        this.doc.setFontSize(10);
        const trendColor = item.trend.startsWith('+') ? [34, 197, 94] : 
                         item.trend.startsWith('-') ? [239, 68, 68] : [107, 114, 128];
        this.doc.setTextColor(...trendColor);
        this.doc.text(item.trend, x + boxWidth - 20, y + 18);
      }
    });

    this.currentY += Math.ceil(this.options.summary.length / 2) * (boxHeight + 10) + 15;
  }

  private addTables(): void {
    this.options.tables.forEach((table, index) => {
      if (index > 0) this.currentY += 15;
      
      this.checkPageBreak(50);

      // Table title
      if (table.title) {
        this.doc.setFontSize(14);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(33, 37, 41);
        this.doc.text(table.title, this.margins.left, this.currentY);
        this.currentY += 8;
      }

      // Generate table
      this.doc.autoTable({
        head: [table.headers],
        body: table.data,
        startY: this.currentY,
        margin: this.margins,
        styles: {
          font: 'helvetica',
          fontSize: 9,
          cellPadding: 5,
          fillColor: [255, 255, 255],
          textColor: [33, 37, 41]
        },
        headStyles: {
          fillColor: [33, 37, 41],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 10
        },
        alternateRowStyles: {
          fillColor: [249, 250, 251]
        },
        footStyles: {
          fillColor: [243, 244, 246],
          textColor: [33, 37, 41],
          fontStyle: 'bold'
        },
        didDrawPage: (data) => {
          this.currentY = data.cursor.y;
        }
      });

      this.currentY += 10;
    });
  }

  private addCharts(): void {
    if (!this.options.charts) return;

    this.options.charts.forEach((chart, index) => {
      this.checkPageBreak(chart.height || 80 + 40);

      // Chart title
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(33, 37, 41);
      this.doc.text(chart.title, this.margins.left, this.currentY);
      this.currentY += 10;

      // Add chart placeholder (in real implementation, this would render actual charts)
      const chartWidth = chart.width || this.pageWidth - this.margins.left - this.margins.right;
      const chartHeight = chart.height || 80;

      this.doc.setDrawColor(229, 231, 235);
      this.doc.setFillColor(249, 250, 251);
      this.doc.roundedRect(
        this.margins.left, 
        this.currentY, 
        chartWidth, 
        chartHeight, 
        3, 
        3, 
        'FD'
      );

      // Add chart type indicator
      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(107, 114, 128);
      this.doc.text(
        `${chart.type.toUpperCase()} CHART`, 
        this.pageWidth / 2, 
        this.currentY + chartHeight / 2, 
        { align: 'center' }
      );

      this.currentY += chartHeight + 15;
    });
  }

  private addFooter(): void {
    const totalPages = this.doc.internal.getNumberOfPages();
    
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i);
      
      // Footer line
      const footerY = this.pageHeight - this.margins.bottom - 10;
      this.doc.setDrawColor(229, 231, 235);
      this.doc.setLineWidth(0.5);
      this.doc.line(this.margins.left, footerY, this.pageWidth - this.margins.right, footerY);

      // Page number
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(107, 114, 128);
      this.doc.text(
        `Page ${i} of ${totalPages}`, 
        this.pageWidth / 2, 
        this.pageHeight - this.margins.bottom, 
        { align: 'center' }
      );

      // Confidentiality notice
      this.doc.setFontSize(8);
      this.doc.text(
        'Confidential - For Internal Use Only',
        this.margins.left,
        this.pageHeight - this.margins.bottom
      );

      // Generated timestamp
      this.doc.text(
        `Generated on ${new Date().toLocaleString()}`,
        this.pageWidth - this.margins.right,
        this.pageHeight - this.margins.bottom,
        { align: 'right' }
      );
    }
  }

  private checkPageBreak(requiredSpace: number): void {
    if (this.currentY + requiredSpace > this.pageHeight - this.margins.bottom - 30) {
      this.doc.addPage();
      this.currentY = this.margins.top;
    }
  }

  private formatFilterValue(key: string, value: any): string {
    if (Array.isArray(value)) {
      return `${key}: ${value.join(', ')}`;
    }
    if (typeof value === 'object' && value !== null) {
      const parts = [];
      if (value.start) parts.push(`From: ${value.start}`);
      if (value.end) parts.push(`To: ${value.end}`);
      return `${key}: ${parts.join(' ')}`;
    }
    return `${key}: ${value}`;
  }
}

// Main PDF generation function
export const generateReportPDF = async (
  reportData: GeneratedReport,
  reportContent: any,
  organizationName: string
): Promise<Blob> => {
  const pdfOptions: PDFOptions = {
    template: {
      title: reportData.report_name,
      subtitle: `${reportData.report_type.charAt(0).toUpperCase() + reportData.report_type.slice(1)} Report`,
      organization: organizationName,
      generatedBy: 'System', // This would come from user data
      generatedAt: new Date(reportData.generated_at).toLocaleString(),
      filters: reportData.parameters
    },
    tables: [],
    charts: [],
    summary: []
  };

  // Process report content based on report type
  if (reportContent.summary) {
    pdfOptions.summary = Object.entries(reportContent.summary).map(([key, value]) => ({
      label: key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
      value: typeof value === 'number' ? value.toLocaleString() : String(value),
      trend: Math.random() > 0.5 ? `+${Math.floor(Math.random() * 20)}%` : `-${Math.floor(Math.random() * 10)}%`
    }));
  }

  // Process table data
  if (reportContent.data && Array.isArray(reportContent.data)) {
    const headers = Object.keys(reportContent.data[0] || {});
    const data = reportContent.data.map((row: any) => 
      headers.map(header => String(row[header] || ''))
    );

    pdfOptions.tables.push({
      title: 'Report Data',
      headers: headers.map(h => h.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())),
      data: data
    });
  }

  // Add charts based on data
  if (reportContent.data && reportContent.data.length > 0) {
    pdfOptions.charts = [
      {
        type: 'bar',
        title: 'Data Visualization',
        data: reportContent.data,
        width: 150,
        height: 80
      }
    ];
  }

  const generator = new PDFGenerator(pdfOptions);
  return generator.generate();
};

// Utility function to download PDF
export const downloadPDF = (blob: Blob, filename: string): void => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Utility function to open PDF in new tab
export const openPDFInNewTab = (blob: Blob): void => {
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
};

// Export functions for different report types
export const generateFinancialReportPDF = async (
  reportData: GeneratedReport,
  financialData: any,
  organizationName: string
): Promise<Blob> => {
  const pdfOptions: PDFOptions = {
    template: {
      title: reportData.report_name,
      subtitle: 'Financial Analysis Report',
      organization: organizationName,
      generatedBy: 'System',
      generatedAt: new Date().toLocaleString(),
      filters: reportData.parameters
    },
    tables: [],
    summary: [
      { label: 'Total Revenue', value: `$${financialData.summary?.totalRevenue?.toLocaleString() || 0}` },
      { label: 'Total Expenses', value: `$${financialData.summary?.totalExpenses?.toLocaleString() || 0}` },
      { label: 'Net Profit', value: `$${financialData.summary?.netProfit?.toLocaleString() || 0}` },
      { label: 'Profit Margin', value: `${financialData.summary?.profitMargin || 0}%` }
    ]
  };

  if (financialData.data) {
    const headers = ['Project', 'Budget', 'Actual', 'Variance', 'Variance %'];
    const data = financialData.data.map((item: any) => [
      item.project_name,
      `$${item.budget_amount?.toLocaleString() || 0}`,
      `$${item.actual_cost?.toLocaleString() || 0}`,
      `$${Math.abs(item.variance || 0).toLocaleString()}`,
      `${item.variance_percentage || 0}%`
    ]);

    pdfOptions.tables.push({
      title: 'Cost Analysis Details',
      headers,
      data
    });
  }

  const generator = new PDFGenerator(pdfOptions);
  return generator.generate();
};

export const generateProjectReportPDF = async (
  reportData: GeneratedReport,
  projectData: any,
  organizationName: string
): Promise<Blob> => {
  const pdfOptions: PDFOptions = {
    template: {
      title: reportData.report_name,
      subtitle: 'Project Portfolio Report',
      organization: organizationName,
      generatedBy: 'System',
      generatedAt: new Date().toLocaleString(),
      filters: reportData.parameters
    },
    tables: [],
    summary: [
      { label: 'Total Projects', value: projectData.summary?.totalProjects?.toLocaleString() || 0 },
      { label: 'Active Projects', value: projectData.summary?.activeProjects?.toLocaleString() || 0 },
      { label: 'Completed Projects', value: projectData.summary?.completedProjects?.toLocaleString() || 0 },
      { label: 'On Schedule', value: `${projectData.summary?.onScheduleProjects || 0}%` }
    ]
  };

  if (projectData.data) {
    const headers = ['Project Name', 'Status', 'Start Date', 'End Date', 'Completion %'];
    const data = projectData.data.map((item: any) => [
      item.project_name,
      item.status,
      item.start_date,
      item.end_date,
      `${item.completion_percentage || 0}%`
    ]);

    pdfOptions.tables.push({
      title: 'Project Portfolio Details',
      headers,
      data
    });
  }

  const generator = new PDFGenerator(pdfOptions);
  return generator.generate();
};

export default PDFGenerator;
